// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqqrae5RiviTJoGRnqOWnYE6f_M92br2s',
    appId: '1:259522194475:web:5c0f31ebed8fab73d0ce6e',
    messagingSenderId: '259522194475',
    projectId: 'testapp1-bc440',
    authDomain: 'testapp1-bc440.firebaseapp.com',
    storageBucket: 'testapp1-bc440.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBsDgpfpWTZBbKfyrTPUtn9MvOmX2TWpE',
    appId: '1:259522194475:android:4df6ccc2c45902ddd0ce6e',
    messagingSenderId: '259522194475',
    projectId: 'testapp1-bc440',
    storageBucket: 'testapp1-bc440.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU_4RGPsFd_jVxNDZmpcZALxaSMS17C2U',
    appId: '1:259522194475:ios:a6d963b02be376fed0ce6e',
    messagingSenderId: '259522194475',
    projectId: 'testapp1-bc440',
    storageBucket: 'testapp1-bc440.firebasestorage.app',
    iosBundleId: 'com.example.testFlutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU_4RGPsFd_jVxNDZmpcZALxaSMS17C2U',
    appId: '1:259522194475:ios:a6d963b02be376fed0ce6e',
    messagingSenderId: '259522194475',
    projectId: 'testapp1-bc440',
    storageBucket: 'testapp1-bc440.firebasestorage.app',
    iosBundleId: 'com.example.testFlutter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqqrae5RiviTJoGRnqOWnYE6f_M92br2s',
    appId: '1:259522194475:web:6ab079e6b9d1e124d0ce6e',
    messagingSenderId: '259522194475',
    projectId: 'testapp1-bc440',
    authDomain: 'testapp1-bc440.firebaseapp.com',
    storageBucket: 'testapp1-bc440.firebasestorage.app',
  );
}
